### ISSUE TITLE
Use consistent default branch name on opf repositories?

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#228] opened 2021-03-23 14:40 UTC
I keep tripping up because the `apps` repository uses `master` but the `argocd-apps` repository uses `main`. Can we just pick one and stick with it? My fingers would thank you.

**Comment by tumido** [comment] 2021-03-23 14:58
Duplicate of: https://github.com/operate-first/blueprint/issues/50 Closing, please discuss it there.

We definitely should do that. It's a tech debt.

**Closed by tumido** 2021-03-23 14:58 UTC
